__author__ = "Sara Zarei, Sajjad Aemmi"
__copyright__ = "Copyright 2020"
__license__ = "GPL"
__version__ = "1.0.5"
__email__ = "sajjadaemmi@gmail.com"
__status__ = "Production"
key = 'farazist_sara71&sajjad73&amir73'
url = 'https://farazist.ir'
local_database_name = 'database.db'